import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactNode } from "react";
import { Center, Container } from "@chakra-ui/react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const Layout = ({
    children
}: {
    children: ReactNode
}) => {

    return (
        <>
            <Head>
                <title>KPI VOYPATI NEXUS</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div
                className={`${geistSans.variable} ${geistMono.variable}`}
            >
                <Center my={10}>
                    <Container>
                        <main >
                            {children}
                        </main>
                    </Container>
                </Center>
                <footer >

                </footer>
            </div>
        </>
    )
}